resources:
  - keel-deployment.yaml
  - datadog-agent.yaml
  - datadog-serviceaccount.yaml
  - vac-benefits-directory-deployment.yaml
  - vac-benefits-directory-service.yaml
  - traefik-ingress-controller-cluster-role-binding.yaml
  - traefik-ingress-controller-cluster-role.yaml
  - traefik-ingress-controller-deployment.yaml
  - traefik-ingress-controller-service-account.yaml
  - traefik-ingress-controller-webui-service.yaml
  - traefik-ingress.yaml
