apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: vac-benefits-directory
  name: vac-benefits-directory
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vac-benefits-directory
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vac-benefits-directory
    spec:
      containers:
        - image: veteransaffairscanada/vac-benefits-directory
          imagePullPolicy: Always
          name: vac-benefits-directory
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: AIRTABLE_WRITE_KEY
              valueFrom:
                secretKeyRef:
                  name: vac-benefits-directory
                  key: airtable_write_key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
